export const STRIPE_PLANS = {
  starter: {
    product_id: "prod_UEuRDMQSWVTnoL",
    price_id: "price_1TGQcwFQlLT8Im0J1OI53niu",
    name: "Starter",
    price: 29,
    features: [
      "Scanner QR code",
      "Cartes de fidélité digitales",
      "Apple Wallet & Google Wallet",
      "Jusqu'à 200 clients",
      "Gestion récompenses",
      "Personnalisation carte",
      "Vitrine publique",
      "Mode hors-ligne (PWA)",
      "Export CSV",
      "Support par email",
    ],
  },
  pro: {
    product_id: "prod_UEuSxVTVVLAifJ",
    price_id: "price_1TGQdDFQlLT8Im0J7YQ9OWuG",
    name: "Pro",
    price: 59,
    popular: true,
    features: [
      "Tout Starter +",
      "Clients illimités",
      "Notifications push ciblées",
      "Campagnes marketing",
      "Automations (relance, anniversaire)",
      "Analytics avancés",
      "Scoring client (Bronze/Silver/Gold)",
      "Gamification (streaks, niveaux)",
      "Avis clients & Google Reviews",
      "Webhooks API",
      "Widget d'inscription",
      "Support prioritaire",
    ],
  },
  franchise: {
    product_id: "prod_FRANCHISE_PLACEHOLDER",
    price_id: "price_FRANCHISE_PLACEHOLDER",
    name: "Franchise",
    price: 149,
    features: [
      "Tout Pro +",
      "Jusqu'à 5 établissements inclus",
      "Dashboard master multi-sites",
      "Comparaison entre points de vente",
      "Managers dédiés par établissement",
      "Carte fidélité unifiée",
      "+29€/établissement supplémentaire",
      "Support dédié",
    ],
  },
} as const;

export type PlanKey = keyof typeof STRIPE_PLANS;
